apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasura
  name: hasura-headless
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: hasura
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: hasura
    hasuraService: custom
  name: hasura
  namespace: default
spec:
  replicas: 1
  serviceName: hasura-headless
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      labels:
        app: hasura
    spec:
      containers:
      - image: hasura/graphql-engine:latest
        imagePullPolicy: IfNotPresent
        name: hasura
        env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          value: postgresql://yugabyte:@yb-tservers.yb-dev-hasura-perf-cluster.svc.cluster.local:5433/hasuratest
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "true"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 4200m
            memory: 8Gi
          requests:
            cpu: "4"
            memory: 8Gi

